token: <YOUR_TOKEN_HERE>
data_root: /dss/mcmlscratch/06/di38riq/scannetpp
root_url: https://kaldir.vc.in.tum.de/scannetpp/download?version=v1&token=TOKEN&file=FILEPATH
download_scenes:
- 09c1414f1b
- 0d2ee665be
- 13c3e046d7
- 1ada7a0617
- 21d970d8de
- 25f3b7a318
- 27dd4da69e
- 286b55a2bf
- 31a2c91c43
- '3864514494'
- 38d58a7a31
- 3db0a1c8f3
- 3e8bba0176
- 3f15a9266d
- 40aec5fffa
- 45b0dac5e3
- 5748ce6f01
- 578511c8a9
- '5942004064'
- 5eb31827b7
- 5ee7c22ba0
- 5f99900f09
- 6115eddb86
- 7831862f02
- 7b6477cb95
- 7bc286c1b6
- 825d228aec
- 9071e139d9
- 99fa5c25e1
- a24f64f7fb
- a8bf42d646
- a980334473
- ac48a9b736
- acd95847c5
- b0a08200c9
- bcd2436daf
- bde1e479ad
- c49a8c6cff
- c4c04e6d6c
- c50d2d1d42
- c5439f4607
- cc5237fd77
- d755b3d9d8
- e398684d27
- e7af285f7d
- f2dc06b1d2
- f3685d06a9
- f3d64c30f8
- f9f95681fd
- fb5a96b1a2
download_assets:
- mesh_aligned_0_05
- dslr_resized_images
- dslr_resized_masks
- dslr_resized_depth
zipped_assets:
- dslr_resized_images
- dslr_resized_masks
- dslr_resized_depth
meta_files:
- splits/nvs_sem_train.txt
- splits/nvs_sem_val.txt
splits:
- nvs_sem_train
- nvs_sem_val
dry_run: false
verbose: true
metadata_only: false
